{
 "title": "HV-VES  connections",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Currently active connections",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hvves_connections_active) by (value)"
    }
   ]
  },
  {
   "title": "Active connections per pod",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(hvves_connections_active) by (kubernetes_pod_name, value)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Active connections over time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(hvves_connections_active)", "legendFormat": "Active connections total" }
   ]
  },
  {
   "title": "Total connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(hvves_connections_total)" }
   ]
  },
  {
   "title": "Clients rejected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(hvves_clients_rejected_total)"
    }
   ]
  },
  {
   "title": "Total connections per pod",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(hvves_connections_total) by (kubernetes_pod_name, value)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Rejected connections per pod",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "sum(hvves_clients_rejected_total) by (kubernetes_pod_name, value)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}