# ============LICENSE_START=======================================================
# dcaegen2-collectors-veshv
# ================================================================================
# Copyright (C) 2019 NOKIA
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============LICENSE_END=========================================================

apiVersion: v1
kind: Pod
metadata:
  generateName: hv-collector-producer-
  namespace: onap
  labels:
    app: hv-collector-producer
spec:
  containers:
    - name: hv-collector-producer
      imagePullPolicy: IfNotPresent
      image: onap/org.onap.dcaegen2.collectors.hv-ves.hv-collector-go-client:latest
      volumeMounts:
        - name: ssl-certs
          mountPath: /ssl
          readOnly: true
      env:
        - name: HV_VES_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: performance-test-config
              key: producer.hvVesAddress
        - name: MSG_SIZE
          valueFrom:
            configMapKeyRef:
              name: performance-test-config
              key: producer.message.size
        - name: MSG_COUNT
          valueFrom:
            configMapKeyRef:
              name: performance-test-config
              key: producer.message.count
        - name: INTERVAL_MS
          valueFrom:
            configMapKeyRef:
              name: performance-test-config
              key: producer.message.interval
        - name: CLIENTS_PER_CONTAINER
          valueFrom:
            configMapKeyRef:
              name: performance-test-config
              key: producer.client.count
        - name: CERT_FILE
          valueFrom:
            configMapKeyRef:
              name: performance-test-config
              key: client.cert.path
        - name: CERT_PASS_FILE
          valueFrom:
            configMapKeyRef:
              name: performance-test-config
              key: client.cert.pass.path
      args: ["--address", "$(HV_VES_ADDRESS)",
             "--clients", "$(CLIENTS_PER_CONTAINER)",
             "--msgsize", "$(MSG_SIZE)",
             "--msgcount", "$(MSG_COUNT)",
             "--intervalms", "$(INTERVAL_MS)",
             "--certfile", "$(CERT_FILE)",
             "--certpass", "$(CERT_PASS_FILE)"]
  volumes:
    - name: ssl-certs
      secret:
        secretName: cert
  restartPolicy: Never
