apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: onap
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      external_labels:
        monitor: 'my-monitor'

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'kafka-processing-consumer'
        metrics_path: '/monitoring/prometheus'
        static_configs:
          - targets: ['kafka-processing-consumer.onap:6063']

      - job_name: 'kafka-offset-consumer'
        metrics_path: '/monitoring/prometheus'
        static_configs:
          - targets: ['kafka-counting-consumer.onap:6062']

      - job_name: 'ves-hv-collector'
        metrics_path: '/monitoring/prometheus'
        static_configs:
          - targets: ['dcae-hv-ves-collector.onap:6060']
