version: "3.5"
services:

  message-router-zookeeper:
    image: nexus3.onap.org:10001/onap/dmaap/zookeeper:4.0.0
    ports:
      - "2181:2181"

  message-router-kafka-0:
    image: nexus3.onap.org:10001/onap/dmaap/kafka111:0.0.6
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      HOST_IP:                                     127.0.0.1
      KAFKA_BROKER_ID:                             0
      ENDPOINT_PORT:                               30490
      KAFKA_ZOOKEEPER_CONNECT:                     "message-router-zookeeper:2181"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE:             "true"
      KAFKA_DELETE_TOPIC_ENABLE:                   "true"

      KAFKA_LISTENERS:                             "INTERNAL_SASL_PLAINTEXT://0.0.0.0:9092,EXTERNAL_SASL_PLAINTEXT://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS:                  "INTERNAL_SASL_PLAINTEXT://message-router-kafka-0:9092,EXTERNAL_SASL_PLAINTEXT://message-router-kafka-0:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:        "INTERNAL_SASL_PLAINTEXT:SASL_PLAINTEXT,EXTERNAL_SASL_PLAINTEXT:SASL_PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME:            "INTERNAL_SASL_PLAINTEXT"
      KAFKA_SASL_ENABLED_MECHANISMS:               "PLAIN"
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL:  "PLAIN"
      KAFKA_AUTHORIZER_CLASS_NAME:                 "org.onap.dmaap.kafkaAuthorize.KafkaCustomAuthorizer"

      aaf_locate_url:                              https://aaf-locate:8095
      KAFKA_LOG_DIRS:                              /opt/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:      1
      KAFKA_DEFAULT_REPLICATION_FACTOR:            1
      KAFKA_NUM_PARTITIONS:                        1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - message-router-zookeeper

  consul-server:
    image: docker.io/consul:1.0.6
    ports:
      - "8500:8500"
    volumes:
      - ./consul/:/consul/config

  consul-bootstrap:
    image: docker.io/consul:1.0.6
    restart: on-failure
    command: ["kv", "put", "-http-addr=http://consul-server:8500", "dcae-hv-ves-collector", '{
                                              "streams_publishes": {
                                                "perf3gpp": {
                                                  "type": "kafka",
                                                  "aaf_credentials": {
                                                    "username": "admin",
                                                    "password": "admin_secret"
                                                  },
                                                  "kafka_info": {
                                                    "bootstrap_servers": "message-router-kafka-0:9093",
                                                    "topic_name": "HV_VES_PERF3GPP"
                                                  }
                                                }
                                              }
                                            }'
    ]
    depends_on:
      - consul-server

  config-binding-service:
    image: nexus3.onap.org:10001/onap/org.onap.dcaegen2.platform.configbinding.app-app:2.2.4
    ports:
      - "10000:10000"
    environment:
      CONSUL_HOST: "consul-server"
    depends_on:
      - consul-bootstrap

  ves-hv-collector:
    image: onap/org.onap.dcaegen2.collectors.hv-ves.hv-collector-main:latest
    ports:
      - "6060:6060"
      - "6061:6061/tcp"
    environment:
      JAVA_OPTS: "-Dio.netty.leakDetection.level=paranoid -Dlogback.configurationFile=/etc/ONAP/dcae-hv-ves-collector/logback.xml"
      VESHV_CONFIGURATION_FILE: "/etc/ves-hv/configuration/base.json"
      CONSUL_HOST: "consul-server"
      CONFIG_BINDING_SERVICE: "CBS"
      HOSTNAME: "dcae-hv-ves-collector"
    healthcheck:
      test: ./healthcheck.sh || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 15s
    depends_on:
      - message-router-kafka-0
      - config-binding-service
    volumes:
      - ./configuration/:/etc/ves-hv/configuration/
      - ./logs:/var/log/ONAP/dcae-hv-ves-collector
      - ../../ssl/:/etc/ves-hv/ssl/

  kafka-consumer:
    image: onap/org.onap.dcaegen2.collectors.hv-ves.hv-collector-kafka-consumer
    ports:
      - "6064:6064/tcp"
    command: ["--listen-port", "6062"]
    depends_on:
      - message-router-kafka-0

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
