{
 "title": "Connections",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Currently active connections - Producers",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(producer_active_connections_total_number)"
    }
   ]
  },
  {
   "title": "Currently active connections - HV-VES",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hvves_connections_active) by (value)",
     "legendFormat": "HV-VES"
    }
   ]
  },
  {
   "title": "Active connections over time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(hvves_connections_active)",
     "legendFormat": "Active connections total - HV-VES"
    },
    {
     "expr": "sum(producer_active_connections_total_number)",
     "legendFormat": "Active connections total - Producers"
    }
   ]
  },
  {
   "title": "Connection rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hvves_connections_active[1s]))",
     "legendFormat": "Connection rate - HV-VES"
    },
    {
     "expr": "sum(rate(producer_active_connections_total_number[1s]))",
     "legendFormat": "Connection rate - Producers"
    }
   ]
  },
  {
   "title": "Total connections - Producers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(producer_all_connections_total_number)"
    }
   ]
  },
  {
   "title": "Total connections - HV-VES",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(hvves_connections_total)" }
   ]
  },
  {
   "title": "Connections failed (producers)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(producer_fail_connections_total_number)"
    }
   ]
  },
  {
   "title": "Clients rejected",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hvves_clients_rejected_total)"
    }
   ]
  },
  {
   "title": "File descriptors open [%]",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_files_open_files/process_files_max_files*100",
     "legendFormat": "hv-ves-collector"
    },
    {
     "expr": "process_open_fds/process_max_fds{pod_name=~\".*producer.*\"}*100",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "node_filefd_allocated/node_filefd_maximum*100",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}