{
 "title": "K8s metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nodes RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\", instance=~\".*worker.*\"}) by(instance) / (sum(machine_memory_bytes{instance=~\".*worker.*\"}) by (instance))*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nodes CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\", instance=~\".*worker.*\"}[1m])) by(instance) / (sum(machine_cpu_cores{instance=~\".*worker.*\"}) by (instance))*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 18, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\".*canal.*\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\".*canal.*\"}[1m]))",
     "legendFormat": "Total Transmit"
    }
   ]
  },
  {
   "title": "Nodes Total RAM Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\"}) by (instance) / (sum(machine_memory_bytes) by (instance))*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nodes Total CPU usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[1m])) by(instance) / (sum(machine_cpu_cores) by (instance))*100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}