{
 "title": "Kafka and Producers Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\".*producer.*\"}[1m]))",
     "legendFormat": "Total Transmit Producers"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\".*kafka-.\"}[1m]))",
     "legendFormat": "Total Transmit Kafka"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{pod=~\".*producer.*\"}[1m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{pod=~\".*kafka-.\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total network usage (producers + hv-ves  + kafka)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\".*kafka-.|.*hv-ves-coll.*|.*producer.*\"}[1m]))",
     "legendFormat": "Total transmit"
    }
   ]
  },
  {
   "title": "HV-VES Network Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{pod=~\"dep-dcae-hv-ves-collector.*\"}[1m])",
     "legendFormat": "receive"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{pod=~\"dep-dcae-hv-ves-collector.*\"}[1m])",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\".*producer.*\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\".*router-kafka.*\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", pod=~\".*kafka-.\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Packets Dropped (producers)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "sum(container_network_transmit_packets_dropped_total{pod=~\".*producer.*\"})",
     "legendFormat": "Packets dropped"
    }
   ]
  },
  {
   "title": "Packets Dropped (hv-ves)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 11 },
   "targets": [
    {
     "expr": "sum(container_network_transmit_packets_dropped_total{pod=~\".*hv-ves-collector.*\"})",
     "legendFormat": "Packets dropped"
    }
   ]
  },
  {
   "title": "Sent (producers)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(container_network_transmit_bytes_total{pod=~\".*producer.*\"})"
    }
   ]
  },
  {
   "title": "Received (hv-ves)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 17 },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{pod=~\".*hv-ves-collector.*\"}",
     "legendFormat": "Packets dropped"
    }
   ]
  }
 ]
}