{
 "title": "HV-VES processing",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(producer_sent_messages_total_number)",
     "legendFormat": "Sent by producers"
    },
    {
     "expr": "sum(hvves_messages_received_total)",
     "legendFormat": "Received by HV-VES"
    },
    { "expr": "sum(hvves_messages_sent_total)", "legendFormat": "Sent by HV-VES" },
    {
     "expr": "sum(hvves_messages_dropped_total)",
     "legendFormat": "Dropped in HV-VES"
    }
   ]
  },
  {
   "title": "Processing time (HV-VES input to HV-VES output with sending to Kafka)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 7, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(hvves_messages_processing_time_seconds_sum[1h])/rate(hvves_messages_processing_time_seconds_count[1h])",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.90, sum( rate(hvves_messages_processing_time_seconds_bucket[1h]) )by(le) )",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum( rate(hvves_messages_processing_time_seconds_bucket[1h]) )by(le) )",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum( rate(hvves_messages_processing_time_seconds_bucket[1h]) )by(le) )",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "Processing time (HV-VES input to HV-VES output without sending to Kafka)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(hvves_messages_processing_time_without_routing_seconds_sum[1h])/rate(hvves_messages_processing_time_without_routing_seconds_count[1h])",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.90, sum( rate(hvves_messages_processing_time_without_routing_seconds_bucket[1h]) )by(le) )",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum( rate(hvves_messages_processing_time_without_routing_seconds_bucket[1h]) )by(le) )",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum( rate(hvves_messages_processing_time_without_routing_seconds_bucket[1h]) )by(le) )",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "Messages rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "msg/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(producer_sent_messages_total_number[1s]))",
     "legendFormat": "Send rate - Producers"
    },
    {
     "expr": "rate(hvves_messages_received_total[1s])",
     "legendFormat": "Receive rate - HV-VES"
    },
    {
     "expr": "rate(hvves_messages_sent_total[1s])",
     "legendFormat": "Send rate - HV-VES"
    }
   ]
  },
  {
   "title": "Total received payload bytes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 13 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hvves_messages_received_payload_bytes_total)"
    }
   ]
  },
  {
   "title": "HV-VES process cpu usage [% of all cores]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(process_cpu_usage) by (kubernetes_pod_name)*100",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Memory usage of HV-VES",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes)/1024/1024/1024\n",
     "legendFormat": "Memory used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes)/1024/1024/1024",
     "legendFormat": "Memory commited"
    }
   ]
  },
  {
   "title": "Average received payload bytes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 15 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hvves_messages_received_payload_bytes_total)/sum(hvves_messages_received_total)"
    }
   ]
  },
  {
   "title": "Messages sent per topic",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(hvves_messages_sent_topic_total) by (topic, value)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages processed per pod",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(hvves_messages_received_total) by (kubernetes_pod_name, value)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}