{
 "title": "HV-VES processing",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Messages received",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(hvves_messages_received_total) by (value)"
    }
   ]
  },
  {
   "title": "Messages dropped",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(hvves_messages_dropped_total)"
    }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(hvves_messages_sent_total)" }
   ]
  },
  {
   "title": "Single message processing time average",
   "type": "graph",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum( rate(hvves_messages_processing_time_seconds_bucket[15m]) )by(le) )",
     "legendFormat": "90th percentile of processing time on pods"
    },
    {
     "expr": "rate(hvves_messages_processing_time_seconds_sum[15m])/rate(hvves_messages_processing_time_seconds_count[15m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hvves_messages_latency_seconds_sum[1h])/rate(hvves_messages_latency_seconds_count[1h])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Total received payload bytes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 12 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hvves_messages_received_payload_bytes_total)"
    }
   ]
  },
  {
   "title": "System cpu usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(process_cpu_usage) by (kubernetes_pod_name)*100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory usage per pod [GB]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 12 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes)/1024/1024/1024\n",
     "legendFormat": "jvm_memory_used_bytes"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes)/1024/1024/1024",
     "legendFormat": "jvm_memory_committed_bytes"
    }
   ]
  },
  {
   "title": "Average received payload bytes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 14 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hvves_messages_received_payload_bytes_total)/sum(hvves_messages_received_total)"
    }
   ]
  },
  {
   "title": "Messages sent per topic",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(hvves_messages_sent_topic_total) by (topic, value)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages processed per pod",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(hvves_messages_received_total) by (kubernetes_pod_name, value)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}