{
 "title": "Producers metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(producer_active_connections_total_number)",
     "legendFormat": "Total"
    },
    {
     "expr": "producer_active_connections_total_number",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Cpu usage [% of core]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{pod_name=~\".*producer.*\"}[60s])",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Successful connections setup time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(producer_histogram_creation_time_successful_connections_sum)/sum(producer_histogram_creation_time_successful_connections_count) * 1000",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(0.9, sum(producer_histogram_creation_time_successful_connections_bucket) by (le)) * 1000",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(producer_histogram_creation_time_successful_connections_bucket) by (le)) * 1000",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(producer_histogram_creation_time_successful_connections_bucket) by (le)) * 1000",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "Connection rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "conn/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(producer_active_connections_total_number[1s]))",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(producer_active_connections_total_number[1s])",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{pod_name=~\".*producer.*\"}",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Producers sending rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(producer_sent_bytes_total_size[1s])*8)",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(producer_sent_bytes_total_size[1s])*8",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Producers sending rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "msg/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(producer_sent_messages_total_number[1s]))",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(producer_sent_messages_total_number[1s])",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Failed connections setup time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(producer_histogram_creation_time_error_connections_sum)/sum(producer_histogram_creation_time_error_connections_count) * 1000",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(0.9, sum(producer_histogram_creation_time_error_connections_bucket) by (le)) * 1000",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(producer_histogram_creation_time_error_connections_bucket) by (le)) * 1000",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(producer_histogram_creation_time_error_connections_bucket) by (le)) * 1000",
     "legendFormat": "99th percentile"
    }
   ]
  }
 ]
}