apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: onap
  labels:
    name: grafana-datasources
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-service:8080
      access: proxy
      isDefault: true