global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka-consumer'
    metrics_path: '/monitoring/prometheus'
    static_configs:
      - targets: ['kafka-consumer:6062']
