FROM openjdk:10-jre-slim

LABEL copyright="Copyright (C) 2018 NOKIA Intellectual Property. All rights reserved."
LABEL license.name="The Apache Software License, Version 2.0"
LABEL license.url="http://www.apache.org/licenses/LICENSE-2.0"
LABEL maintainer="Nokia Wroclaw ONAP Team"
